apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: result
  name: result
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  strategy:
    canary:
      # optional: define a stable service (for traffic routing)
      stableService: result   # must exist
      steps:
      - setWeight: 20          # send 20% traffic to canary
      - pause: {}              # wait for manual promotion (via CLI or UI)
      - setWeight: 40
      - pause: {duration: 30}  # wait 30 seconds automatically
      - setWeight: 60
      - pause: {duration: 30}
      - setWeight: 80
      - pause: {duration: 30}
      # after all steps, remaining 100% goes to new version automatically
  template:
    metadata:
      labels:
        app: result
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - image: docker.io/dockersamples/examplevotingapp_result:before
        name: result
        ports:
        - containerPort: 80
          name: result
