apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: voting-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - image: docker.io/dockersamples/examplevotingapp_worker
        name: worker
        env:
          - name: POSTGRES_HOST
            value: postgres.voting-db.svc.cluster.local

          - name: POSTGRES_PORT
            value: "5432"